# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8072f11823bbf7bad49afda4ccc46f0ed17dbbf7ae1be95721bede5263af8266fbfc3c3b632855962451919cac8d583609d6ddb9a9b22b94f08cc0e7feb952ce

test:
  secret_key_base: 5314f72e51610bd51acf2a22a7490f964216d3304b883e3fead60c486c31105478b78aaa15d94dd2f06db23c9298611cd5de5a5fd507cddb6a5a5aadd2f7a305

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
